
services:
  metastore:
    image: infravibe/atlas-hive:4.0.1
    platform: linux/amd64
    restart: unless-stopped
    container_name: metastore
    hostname: metastore
    environment:
      DB_DRIVER: postgres
      SERVICE_NAME: 'metastore'
      SERVICE_OPTS: '-Xmx1G -Djavax.jdo.option.ConnectionDriverName=org.postgresql.Driver
                     -Djavax.jdo.option.ConnectionURL=jdbc:postgresql://postgres:5432/metastore_db
                     -Djavax.jdo.option.ConnectionUserName=hive
                     -Djavax.jdo.option.ConnectionPassword=password'
    ports:
      - '9083:9083'
    volumes:
      - ./conf/hive/metastore:/opt/hive/conf
      - ./conf/postgres/postgresql-42.7.4.jar:/opt/hive/lib/postgresql-42.7.4.jar
      - ./conf/aws/aws-java-sdk-bundle-1.12.262.jar:/opt/hive/lib/aws-java-sdk-bundle-1.12.262.jar
      - ./conf/hadoop/hadoop-aws-3.3.4.jar:/opt/hive/lib/hadoop-aws-3.3.4.jar
    healthcheck:
      test: [ "CMD-SHELL", "/opt/hive/bin/schematool -dbType postgres -info >/dev/null 2>&1 || exit 1" ]
      interval: 15s
      timeout: 10s
      retries: 5
    networks:
      - apache

  hiveserver2:
    image: infravibe/atlas-hive:4.0.1
    platform: linux/amd64
    user: root
    depends_on:
      metastore:
        condition: service_healthy
    restart: unless-stopped
    container_name: hiveserver2
    environment:
#      HIVE_SERVER2_THRIFT_PORT: 10000
#      SERVICE_OPTS: '-Xmx1G -Dhive.metastore.uris=thrift://metastore:9083'
      IS_RESUME: 'true'
      SERVICE_NAME: 'hiveserver2'
    volumes:
      - ./conf/hive/hiveserver2:/opt/hive/conf
      - ./conf/postgres/postgresql-42.7.4.jar:/opt/hive/lib/postgresql-42.7.4.jar
      - ./conf/aws/aws-java-sdk-bundle-1.12.262.jar:/opt/hive/lib/aws-java-sdk-bundle-1.12.262.jar
      - ./conf/hadoop/hadoop-aws-3.3.4.jar:/opt/hive/lib/hadoop-aws-3.3.4.jar
    ports:
      - '10000:10000'
      - '10002:10002'
    networks:
      - apache

networks:
  apache:
    external: true
    name: apache