
services:
  postgres:
    image: postgres:15
    platform: linux/amd64
    environment:
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
      POSTGRES_DB: metastore
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - apache

  hive-metastore:
    image: apache/hive:3.1.3
    platform: linux/amd64
    environment:
      - SERVICE_NAME=metastore
      - DB_DRIVER=postgres
      - PGPASSWORD=hive
    ports:
      - "9083:9083"
    volumes:
      - ./conf:/opt/hive/conf
      - ./conf/postgres/postgresql-42.7.4.jar:/opt/hive/lib/postgresql.jar
    networks:
      - apache
    depends_on:
      - postgres
#    command: bash -c "/opt/hive/bin/schematool -dbType postgres -initSchema && /opt/hive/bin/hive --service metastore --hiveconf hive.root.logger=INFO,console"
    command: >
      bash -c '
        echo "Waiting for PostgreSQL to be ready...";
        until pg_isready -h postgres -U hive -d metastore; do
          sleep 2;
        done;
        echo "PostgreSQL is ready.";
        echo "Attempting to initialize or upgrade Hive schema...";
        /opt/hive/bin/schematool -dbType postgres -initOrUpgradeSchema;
        if [ $$? -ne 0 ]; then
          echo "Schema initialization/upgrade FAILED! Check logs above for details.";
          exit 1;
        fi;
        echo "Hive schema is ready or successfully upgraded.";
        echo "Starting Hive Metastore service...";
        /opt/hive/bin/hive --service metastore --hiveconf hive.root.logger=INFO,console
      '

  hive-server2:
    image: apache/hive:3.1.3
    platform: linux/amd64
    environment:
      - SERVICE_NAME=hiveserver2
      - DB_DRIVER=postgres
    volumes:
      - ./conf:/opt/hive/conf
      - ./conf/postgres/postgresql-42.7.4.jar:/opt/hive/lib/postgresql.jar
    networks:
      - apache
    depends_on:
      - hive-metastore
    ports:
      - "10000:10000"
      - "10002:10002"
      - "9999:9999"
    command: /opt/hive/bin/hive --service hiveserver2

networks:
  apache:
    external: true
    name: apache

volumes:
  postgres_data: