services:
  hive-postgres:
    image: postgres:17.2-bookworm
    environment:
      POSTGRES_PASSWORD: "hive"
    ports:
      - "5432:5432"
    volumes:
      - hive_postgres_data:/var/lib/postgresql/data
    networks:
      - apache

  hive-metastore:
    image: apache/hive:4.0.1
    platform: linux/amd64
    container_name: hive-metastore
    depends_on:
      - hive-postgres
    environment:
      SERVICE_NAME: metastore
      DB_DRIVER: postgres
      SERVICE_OPTS: >-
        -Djavax.jdo.option.ConnectionDriverName=org.postgresql.Driver
        -Djavax.jdo.option.ConnectionURL=jdbc:postgresql://hive-postgres:5432/postgres
        -Djavax.jdo.option.ConnectionUserName=postgres
        -Djavax.jdo.option.ConnectionPassword=hive
        -Dhive.metastore.warehouse.dir=hdfs://namenode:9820/user/hive/warehouse
        -Dfs.defaultFS=hdfs://namenode:9820
    ports:
      - "9083:9083"
    volumes:
      - ./conf/postgres/postgresql-42.7.5.jar:/opt/hive/lib/postgres.jar
    networks:
      - apache

  hiveserver2:
    image: apache/hive:4.0.1
    platform: linux/amd64
    container_name: hiveserver2
    depends_on:
      - hive-metastore
    environment:
      SERVICE_NAME: hiveserver2
      IS_RESUME: true
      SERVICE_OPTS: >-
        -Djavax.jdo.option.ConnectionDriverName=org.postgresql.Driver
        -Djavax.jdo.option.ConnectionURL=jdbc:postgresql://hive-postgres:5432/postgres
        -Djavax.jdo.option.ConnectionUserName=postgres
        -Djavax.jdo.option.ConnectionPassword=hive
        -Dhive.metastore.uris=thrift://hive-metastore:9083
        -Dhive.metastore.warehouse.dir=hdfs://namenode:9820/user/hive/warehouse
        -Dfs.defaultFS=hdfs://namenode:9820
    volumes:
      - ./conf/postgres/postgresql-42.7.5.jar:/opt/hive/lib/postgres.jar
    ports:
      - "10000:10000"
      - "10002:10002"
    networks:
      - apache

volumes:
  hive_postgres_data:

networks:
  apache:
    external: true
    name: apache